services:
  - type: web
    name: Cabeleireiro
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Cabeleireiro.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cabeleireiro-db
          property: connectionString
      - key: DEBUG
        value: "False"
