# Generated by Django 5.2.4 on 2025-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cortes/')),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
